# nn.CrossEntropyLoss, F.softmax, F.log_softmax, F.nll_loss()

In [2]:
from fastai.vision.all import *

In [52]:
batch_size = 5
n_classes = 3

W = torch.randn(9, n_classes)
b = torch.randn(1)
X = torch.randn(batch_size, 9)
y = F.relu(X@W + b)
y.shape, y

(torch.Size([5, 3]),
 tensor([[2.8238, 7.4035, 0.0000],
         [4.0516, 1.9607, 5.3125],
         [0.0000, 0.1175, 0.2113],
         [1.3030, 0.0000, 5.0081],
         [0.0000, 0.0000, 7.8666]]))

target {0,1,2}

In [41]:
t = torch.empty(batch_size, dtype=torch.long).random_(n_classes)
t

tensor([0, 1, 2, 1, 2])

In [42]:
loss = nn.CrossEntropyLoss()(y, t)
loss

tensor(2.5016)

In [43]:
F.nll_loss(F.log_softmax(y, dim=1), t)

tensor(2.5016)

In [44]:
y.softmax(dim=1)

tensor([[2.8882e-02, 3.4899e-01, 6.2212e-01],
        [2.4541e-03, 8.4614e-04, 9.9670e-01],
        [1.3856e-01, 3.2859e-02, 8.2858e-01],
        [3.3355e-02, 9.5331e-01, 1.3336e-02],
        [2.1736e-01, 5.9117e-01, 1.9147e-01]])

In [45]:
y.softmax(dim=1).sum(dim=1)

tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000])

In [46]:
y.log_softmax(dim=1).sum(dim=1)

tensor([ -5.0719, -13.0881,  -5.5800,  -7.7657,  -3.7049])

In [47]:
y.softmax(dim=1).log().sum(dim=1)

tensor([ -5.0719, -13.0881,  -5.5800,  -7.7657,  -3.7049])

In [48]:
F.nll_loss(y.softmax(dim=1).log(), t)

tensor(2.5016)

In [53]:
y0 = y.softmax(dim=1)
y0 = y0.log()
y0 = y0[range(batch_size), t.tolist()]
y0 = -y0.mean()
y0

tensor(2.8518)

In [54]:
nn.CrossEntropyLoss()(y, t)

tensor(2.8518)