# nn.CrossEntropyLoss, F.softmax, F.log_softmax, F.nll_loss()

In [2]:
from fastai.vision.all import *

In [91]:
y = torch.randn((6, 3))
y

tensor([[-0.0140, -0.5906,  2.3905],
        [ 0.9921, -0.2100, -0.8631],
        [-0.0901, -1.0944,  0.5427],
        [ 2.2431,  0.3458, -0.0150],
        [-1.2485,  1.3326, -0.0441],
        [-1.1257, -0.0526,  0.5224]])

In [149]:
t = torch.empty(6, dtype=torch.long).random_(3)
t

tensor([1, 2, 2, 1, 1, 2])

In [193]:
loss = nn.CrossEntropyLoss(reduction='none')(y, t)
loss

tensor([3.1130, 2.2316, 0.5456, 2.1240, 0.2837, 0.5626])

In [191]:
F.nll_loss(F.log_softmax(y, dim=1), t, reduction='none')

tensor([3.1130, 2.2316, 0.5456, 2.1240, 0.2837, 0.5626])

In [154]:
y.softmax(dim=1)

tensor([[0.0791, 0.0445, 0.8764],
        [0.6864, 0.2063, 0.1074],
        [0.3078, 0.1127, 0.5795],
        [0.7971, 0.1195, 0.0833],
        [0.0570, 0.7530, 0.1900],
        [0.1096, 0.3206, 0.5697]])

In [155]:
y.softmax(dim=1).sum(dim=1)

tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000])

In [156]:
y.log_softmax(dim=1).sum(dim=1)

tensor([-5.7814, -4.1864, -3.9067, -4.8356, -4.8091, -3.9107])

In [157]:
y.softmax(dim=1).log().sum(dim=1)

tensor([-5.7814, -4.1864, -3.9067, -4.8356, -4.8091, -3.9107])

In [194]:
F.nll_loss(y.log_softmax(dim=1), t, reduction='none')

tensor([3.1130, 2.2316, 0.5456, 2.1240, 0.2837, 0.5626])

In [163]:
idx = list(zip(range(6), t.tolist()))
idx

[(0, 1), (1, 2), (2, 2), (3, 1), (4, 1), (5, 2)]

In [195]:
[y.log_softmax(dim=1)[i,j] for i,j in list(zip(range(6), t.tolist()))]

[tensor(-3.1130),
 tensor(-2.2316),
 tensor(-0.5456),
 tensor(-2.1240),
 tensor(-0.2837),
 tensor(-0.5626)]

In [196]:
y.log_softmax(dim=1)[range(6), t.tolist()]

tensor([-3.1130, -2.2316, -0.5456, -2.1240, -0.2837, -0.5626])

In [201]:
-sum(y.log_softmax(dim=1)[range(6), t.tolist()])

tensor(8.8605)

In [203]:
nn.CrossEntropyLoss(reduction='sum')(y, t), nn.CrossEntropyLoss(reduction='mean')(y, t)

(tensor(8.8605), tensor(1.4768))